//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazWeb.ServiceReference1Prod {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqBody", Namespace="http://www.uruware.com/ucfe/inbox/webservice")]
    [System.SerializableAttribute()]
    public partial class ReqBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HMACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InterfazWeb.ServiceReference1Prod.RequerimientoParaUcfe ReqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReqEncField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodComercioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTerminalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HMAC {
            get {
                return this.HMACField;
            }
            set {
                if ((object.ReferenceEquals(this.HMACField, value) != true)) {
                    this.HMACField = value;
                    this.RaisePropertyChanged("HMAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InterfazWeb.ServiceReference1Prod.RequerimientoParaUcfe Req {
            get {
                return this.ReqField;
            }
            set {
                if ((object.ReferenceEquals(this.ReqField, value) != true)) {
                    this.ReqField = value;
                    this.RaisePropertyChanged("Req");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestDateField, value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tout {
            get {
                return this.ToutField;
            }
            set {
                if ((this.ToutField.Equals(value) != true)) {
                    this.ToutField = value;
                    this.RaisePropertyChanged("Tout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ReqEnc {
            get {
                return this.ReqEncField;
            }
            set {
                if ((object.ReferenceEquals(this.ReqEncField, value) != true)) {
                    this.ReqEncField = value;
                    this.RaisePropertyChanged("ReqEnc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CodComercio {
            get {
                return this.CodComercioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodComercioField, value) != true)) {
                    this.CodComercioField = value;
                    this.RaisePropertyChanged("CodComercio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string CodTerminal {
            get {
                return this.CodTerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTerminalField, value) != true)) {
                    this.CodTerminalField = value;
                    this.RaisePropertyChanged("CodTerminal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequerimientoParaUcfe", Namespace="http://www.uruware.com/ucfe/inbox/webservice")]
    [System.SerializableAttribute()]
    public partial class RequerimientoParaUcfe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CfeXmlOTextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CifrarComplementoFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodComercioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodRtaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatosQrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailEnvioPdfReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoSituacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaReqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraReqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdReqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImpresoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCfeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RechComField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCfeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adenda {
            get {
                return this.AdendaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdendaField, value) != true)) {
                    this.AdendaField = value;
                    this.RaisePropertyChanged("Adenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Certificado {
            get {
                return this.CertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificadoField, value) != true)) {
                    this.CertificadoField = value;
                    this.RaisePropertyChanged("Certificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CfeXmlOTexto {
            get {
                return this.CfeXmlOTextoField;
            }
            set {
                if ((object.ReferenceEquals(this.CfeXmlOTextoField, value) != true)) {
                    this.CfeXmlOTextoField = value;
                    this.RaisePropertyChanged("CfeXmlOTexto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CifrarComplementoFiscal {
            get {
                return this.CifrarComplementoFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.CifrarComplementoFiscalField, value) != true)) {
                    this.CifrarComplementoFiscalField = value;
                    this.RaisePropertyChanged("CifrarComplementoFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodComercio {
            get {
                return this.CodComercioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodComercioField, value) != true)) {
                    this.CodComercioField = value;
                    this.RaisePropertyChanged("CodComercio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodRta {
            get {
                return this.CodRtaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodRtaField, value) != true)) {
                    this.CodRtaField = value;
                    this.RaisePropertyChanged("CodRta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTerminal {
            get {
                return this.CodTerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTerminalField, value) != true)) {
                    this.CodTerminalField = value;
                    this.RaisePropertyChanged("CodTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatosQr {
            get {
                return this.DatosQrField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosQrField, value) != true)) {
                    this.DatosQrField = value;
                    this.RaisePropertyChanged("DatosQr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailEnvioPdfReceptor {
            get {
                return this.EmailEnvioPdfReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailEnvioPdfReceptorField, value) != true)) {
                    this.EmailEnvioPdfReceptorField = value;
                    this.RaisePropertyChanged("EmailEnvioPdfReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoSituacion {
            get {
                return this.EstadoSituacionField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoSituacionField, value) != true)) {
                    this.EstadoSituacionField = value;
                    this.RaisePropertyChanged("EstadoSituacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaReq {
            get {
                return this.FechaReqField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaReqField, value) != true)) {
                    this.FechaReqField = value;
                    this.RaisePropertyChanged("FechaReq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraReq {
            get {
                return this.HoraReqField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraReqField, value) != true)) {
                    this.HoraReqField = value;
                    this.RaisePropertyChanged("HoraReq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdReq {
            get {
                return this.IdReqField;
            }
            set {
                if ((object.ReferenceEquals(this.IdReqField, value) != true)) {
                    this.IdReqField = value;
                    this.RaisePropertyChanged("IdReq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impresora {
            get {
                return this.ImpresoraField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpresoraField, value) != true)) {
                    this.ImpresoraField = value;
                    this.RaisePropertyChanged("Impresora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCfe {
            get {
                return this.NumeroCfeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCfeField, value) != true)) {
                    this.NumeroCfeField = value;
                    this.RaisePropertyChanged("NumeroCfe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RechCom {
            get {
                return this.RechComField;
            }
            set {
                if ((object.ReferenceEquals(this.RechComField, value) != true)) {
                    this.RechComField = value;
                    this.RaisePropertyChanged("RechCom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutEmisor {
            get {
                return this.RutEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.RutEmisorField, value) != true)) {
                    this.RutEmisorField = value;
                    this.RaisePropertyChanged("RutEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCfe {
            get {
                return this.TipoCfeField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCfeField, value) != true)) {
                    this.TipoCfeField = value;
                    this.RaisePropertyChanged("TipoCfe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoMensaje {
            get {
                return this.TipoMensajeField;
            }
            set {
                if ((this.TipoMensajeField.Equals(value) != true)) {
                    this.TipoMensajeField = value;
                    this.RaisePropertyChanged("TipoMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uuid {
            get {
                return this.UuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UuidField, value) != true)) {
                    this.UuidField = value;
                    this.RaisePropertyChanged("Uuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespBody", Namespace="http://schemas.datacontract.org/2004/07/Uruware.Ucfe.Inbox.WebService")]
    [System.SerializableAttribute()]
    public partial class RespBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InterfazWeb.ServiceReference1Prod.RespuestaDeUcfe RespField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespEncField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InterfazWeb.ServiceReference1Prod.RespuestaDeUcfe Resp {
            get {
                return this.RespField;
            }
            set {
                if ((object.ReferenceEquals(this.RespField, value) != true)) {
                    this.RespField = value;
                    this.RaisePropertyChanged("Resp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RespEnc {
            get {
                return this.RespEncField;
            }
            set {
                if ((object.ReferenceEquals(this.RespEncField, value) != true)) {
                    this.RespEncField = value;
                    this.RaisePropertyChanged("RespEnc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaDeUcfe", Namespace="http://www.uruware.com/ucfe/inbox/webservice")]
    [System.SerializableAttribute()]
    public partial class RespuestaDeUcfe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaeNroDesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaeNroHastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificadoParaFirmarCfeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveCertificadoFirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodComercioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodRtaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSeguridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatosQrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoEnDgiCfeRecibidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoSituacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtiquetasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaReqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraReqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCaeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdReqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenQrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeRtaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCfeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RangoDesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RangoHastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCfeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VencimientoCaeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlCfeFirmadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adenda {
            get {
                return this.AdendaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdendaField, value) != true)) {
                    this.AdendaField = value;
                    this.RaisePropertyChanged("Adenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaeNroDesde {
            get {
                return this.CaeNroDesdeField;
            }
            set {
                if ((object.ReferenceEquals(this.CaeNroDesdeField, value) != true)) {
                    this.CaeNroDesdeField = value;
                    this.RaisePropertyChanged("CaeNroDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaeNroHasta {
            get {
                return this.CaeNroHastaField;
            }
            set {
                if ((object.ReferenceEquals(this.CaeNroHastaField, value) != true)) {
                    this.CaeNroHastaField = value;
                    this.RaisePropertyChanged("CaeNroHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Certificado {
            get {
                return this.CertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificadoField, value) != true)) {
                    this.CertificadoField = value;
                    this.RaisePropertyChanged("Certificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificadoParaFirmarCfe {
            get {
                return this.CertificadoParaFirmarCfeField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificadoParaFirmarCfeField, value) != true)) {
                    this.CertificadoParaFirmarCfeField = value;
                    this.RaisePropertyChanged("CertificadoParaFirmarCfe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveCertificadoFirma {
            get {
                return this.ClaveCertificadoFirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveCertificadoFirmaField, value) != true)) {
                    this.ClaveCertificadoFirmaField = value;
                    this.RaisePropertyChanged("ClaveCertificadoFirma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodComercio {
            get {
                return this.CodComercioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodComercioField, value) != true)) {
                    this.CodComercioField = value;
                    this.RaisePropertyChanged("CodComercio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodRta {
            get {
                return this.CodRtaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodRtaField, value) != true)) {
                    this.CodRtaField = value;
                    this.RaisePropertyChanged("CodRta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTerminal {
            get {
                return this.CodTerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTerminalField, value) != true)) {
                    this.CodTerminalField = value;
                    this.RaisePropertyChanged("CodTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSeguridad {
            get {
                return this.CodigoSeguridadField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSeguridadField, value) != true)) {
                    this.CodigoSeguridadField = value;
                    this.RaisePropertyChanged("CodigoSeguridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatosQr {
            get {
                return this.DatosQrField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosQrField, value) != true)) {
                    this.DatosQrField = value;
                    this.RaisePropertyChanged("DatosQr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoEnDgiCfeRecibido {
            get {
                return this.EstadoEnDgiCfeRecibidoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoEnDgiCfeRecibidoField, value) != true)) {
                    this.EstadoEnDgiCfeRecibidoField = value;
                    this.RaisePropertyChanged("EstadoEnDgiCfeRecibido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoSituacion {
            get {
                return this.EstadoSituacionField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoSituacionField, value) != true)) {
                    this.EstadoSituacionField = value;
                    this.RaisePropertyChanged("EstadoSituacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etiquetas {
            get {
                return this.EtiquetasField;
            }
            set {
                if ((object.ReferenceEquals(this.EtiquetasField, value) != true)) {
                    this.EtiquetasField = value;
                    this.RaisePropertyChanged("Etiquetas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFirma {
            get {
                return this.FechaFirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFirmaField, value) != true)) {
                    this.FechaFirmaField = value;
                    this.RaisePropertyChanged("FechaFirma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaReq {
            get {
                return this.FechaReqField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaReqField, value) != true)) {
                    this.FechaReqField = value;
                    this.RaisePropertyChanged("FechaReq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraReq {
            get {
                return this.HoraReqField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraReqField, value) != true)) {
                    this.HoraReqField = value;
                    this.RaisePropertyChanged("HoraReq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCae {
            get {
                return this.IdCaeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCaeField, value) != true)) {
                    this.IdCaeField = value;
                    this.RaisePropertyChanged("IdCae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdReq {
            get {
                return this.IdReqField;
            }
            set {
                if ((object.ReferenceEquals(this.IdReqField, value) != true)) {
                    this.IdReqField = value;
                    this.RaisePropertyChanged("IdReq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImagenQr {
            get {
                return this.ImagenQrField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenQrField, value) != true)) {
                    this.ImagenQrField = value;
                    this.RaisePropertyChanged("ImagenQr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRta {
            get {
                return this.MensajeRtaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRtaField, value) != true)) {
                    this.MensajeRtaField = value;
                    this.RaisePropertyChanged("MensajeRta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCfe {
            get {
                return this.NumeroCfeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCfeField, value) != true)) {
                    this.NumeroCfeField = value;
                    this.RaisePropertyChanged("NumeroCfe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RangoDesde {
            get {
                return this.RangoDesdeField;
            }
            set {
                if ((object.ReferenceEquals(this.RangoDesdeField, value) != true)) {
                    this.RangoDesdeField = value;
                    this.RaisePropertyChanged("RangoDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RangoHasta {
            get {
                return this.RangoHastaField;
            }
            set {
                if ((object.ReferenceEquals(this.RangoHastaField, value) != true)) {
                    this.RangoHastaField = value;
                    this.RaisePropertyChanged("RangoHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutEmisor {
            get {
                return this.RutEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.RutEmisorField, value) != true)) {
                    this.RutEmisorField = value;
                    this.RaisePropertyChanged("RutEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCfe {
            get {
                return this.TipoCfeField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCfeField, value) != true)) {
                    this.TipoCfeField = value;
                    this.RaisePropertyChanged("TipoCfe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoMensaje {
            get {
                return this.TipoMensajeField;
            }
            set {
                if ((this.TipoMensajeField.Equals(value) != true)) {
                    this.TipoMensajeField = value;
                    this.RaisePropertyChanged("TipoMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uuid {
            get {
                return this.UuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UuidField, value) != true)) {
                    this.UuidField = value;
                    this.RaisePropertyChanged("Uuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VencimientoCae {
            get {
                return this.VencimientoCaeField;
            }
            set {
                if ((object.ReferenceEquals(this.VencimientoCaeField, value) != true)) {
                    this.VencimientoCaeField = value;
                    this.RaisePropertyChanged("VencimientoCae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlCfeFirmado {
            get {
                return this.XmlCfeFirmadoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlCfeFirmadoField, value) != true)) {
                    this.XmlCfeFirmadoField = value;
                    this.RaisePropertyChanged("XmlCfeFirmado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.uruware.com/ucfe/inbox/webservice", ConfigurationName="ServiceReference1Prod.ICfeService")]
    public interface ICfeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.uruware.com/ucfe/inbox/webservice/ICfeService/Invoke", ReplyAction="http://www.uruware.com/ucfe/inbox/webservice/ICfeService/InvokeResponse")]
        InterfazWeb.ServiceReference1Prod.RespBody Invoke(InterfazWeb.ServiceReference1Prod.ReqBody req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICfeServiceChannel : InterfazWeb.ServiceReference1Prod.ICfeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CfeServiceClient : System.ServiceModel.ClientBase<InterfazWeb.ServiceReference1Prod.ICfeService>, InterfazWeb.ServiceReference1Prod.ICfeService {
        
        public CfeServiceClient() {
        }
        
        public CfeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CfeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CfeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CfeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InterfazWeb.ServiceReference1Prod.RespBody Invoke(InterfazWeb.ServiceReference1Prod.ReqBody req) {
            return base.Channel.Invoke(req);
        }
    }
}
