//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazWeb.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comprobante", Namespace="http://schemas.datacontract.org/2004/07/TrxServer.Cfe.WebServices")]
    [System.SerializableAttribute()]
    public partial class Comprobante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoComercioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoCfeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoComercio {
            get {
                return this.CodigoComercioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoComercioField, value) != true)) {
                    this.CodigoComercioField = value;
                    this.RaisePropertyChanged("CodigoComercio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTerminal {
            get {
                return this.CodigoTerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTerminalField, value) != true)) {
                    this.CodigoTerminalField = value;
                    this.RaisePropertyChanged("CodigoTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoCfe {
            get {
                return this.TipoCfeField;
            }
            set {
                if ((this.TipoCfeField.Equals(value) != true)) {
                    this.TipoCfeField = value;
                    this.RaisePropertyChanged("TipoCfe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uuid {
            get {
                return this.UuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UuidField, value) != true)) {
                    this.UuidField = value;
                    this.RaisePropertyChanged("Uuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConsultaCfe", Namespace="http://schemas.datacontract.org/2004/07/TrxServer.Cfe.WebServices")]
    [System.SerializableAttribute()]
    public partial class RespuestaConsultaCfe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoComercioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoCfeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlTransformadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoComercio {
            get {
                return this.CodigoComercioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoComercioField, value) != true)) {
                    this.CodigoComercioField = value;
                    this.RaisePropertyChanged("CodigoComercio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTerminal {
            get {
                return this.CodigoTerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTerminalField, value) != true)) {
                    this.CodigoTerminalField = value;
                    this.RaisePropertyChanged("CodigoTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFirma {
            get {
                return this.FechaFirmaField;
            }
            set {
                if ((this.FechaFirmaField.Equals(value) != true)) {
                    this.FechaFirmaField = value;
                    this.RaisePropertyChanged("FechaFirma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoCfe {
            get {
                return this.TipoCfeField;
            }
            set {
                if ((this.TipoCfeField.Equals(value) != true)) {
                    this.TipoCfeField = value;
                    this.RaisePropertyChanged("TipoCfe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlTransformado {
            get {
                return this.XmlTransformadoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlTransformadoField, value) != true)) {
                    this.XmlTransformadoField = value;
                    this.RaisePropertyChanged("XmlTransformado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoCfeRecibido", Namespace="http://schemas.datacontract.org/2004/07/TrxServer.Cfe.Common")]
    public enum EstadoCfeRecibido : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebeSerEnviadoAlErp = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnviadoAlErpSeEsperaRespuesta = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aceptado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rechazado = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Anulado = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ucfe.uruware.com/", ConfigurationName="ServiceReference2.IConsultaCfe")]
    public interface IConsultaCfe {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorEmpresaDenegadosPorDgi", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorEmpresaDenegadosPorDgiRespons" +
            "e")]
        InterfazWeb.ServiceReference2.Comprobante[] ComprobantesPorEmpresaDenegadosPorDgi(string rut, System.DateTime fechaComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorEmpresaPorSerEnviadosADgi", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorEmpresaPorSerEnviadosADgiResp" +
            "onse")]
        int ComprobantesPorEmpresaPorSerEnviadosADgi(string rut, System.DateTime fechaComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorSucursalDenegadosPorDgi", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorSucursalDenegadosPorDgiRespon" +
            "se")]
        InterfazWeb.ServiceReference2.Comprobante[] ComprobantesPorSucursalDenegadosPorDgi(string codigoComercio, System.DateTime fechaComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorSucursalPorSerEnviadosADgi", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorSucursalPorSerEnviadosADgiRes" +
            "ponse")]
        int ComprobantesPorSucursalPorSerEnviadosADgi(string codigoComercio, System.DateTime fechaComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorCajaDenegadosPorDgi", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorCajaDenegadosPorDgiResponse")]
        InterfazWeb.ServiceReference2.Comprobante[] ComprobantesPorCajaDenegadosPorDgi(string codigoTerminal, System.DateTime fechaComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorCajaPorSerEnviadosADgi", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ComprobantesPorCajaPorSerEnviadosADgiRespons" +
            "e")]
        int ComprobantesPorCajaPorSerEnviadosADgi(string codigoTerminal, System.DateTime fechaComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ConsultaHtmlPorNumero", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ConsultaHtmlPorNumeroResponse")]
        string ConsultaHtmlPorNumero(string rut, int tipoCfe, string serieCfe, int numeroCfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ConsultaHtmlConMontoYCodigo", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ConsultaHtmlConMontoYCodigoResponse")]
        string ConsultaHtmlConMontoYCodigo(string rut, int tipoCfe, string serieCfe, int numeroCfe, string monto, string codigoSeguridad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ConsultaAvanzadaConMontoYCodigo", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ConsultaAvanzadaConMontoYCodigoResponse")]
        InterfazWeb.ServiceReference2.RespuestaConsultaCfe ConsultaAvanzadaConMontoYCodigo(string rut, int tipoCfe, string serieCfe, int numeroCfe, string monto, string codigoSeguridad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ObtenerPdf", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ObtenerPdfResponse")]
        byte[] ObtenerPdf(string rut, int tipoCfe, string serieCfe, int numeroCfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/GenerarImagen", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/GenerarImagenResponse")]
        byte[][] GenerarImagen(string rut, int tipoCfe, string serieCfe, int numeroCfe, string formato, int dpiX, int dpiY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ObtenerPdfConParametros", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ObtenerPdfConParametrosResponse")]
        byte[] ObtenerPdfConParametros(string rut, int tipoCfe, string serieCfe, int numeroCfe, string[] nombreParametros, string[] valoresParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/GenerarImagenConParametros", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/GenerarImagenConParametrosResponse")]
        byte[][] GenerarImagenConParametros(string rut, int tipoCfe, string serieCfe, int numeroCfe, string formato, int dpiX, int dpiY, string[] nombreParametros, string[] valoresParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ObtenerPdfCfeRecibido", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ObtenerPdfCfeRecibidoResponse")]
        byte[] ObtenerPdfCfeRecibido(string rut, string rutRecibido, int tipoCfe, string serieCfe, int numeroCfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/ObtenerEstadoCfeRecibido", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/ObtenerEstadoCfeRecibidoResponse")]
        InterfazWeb.ServiceReference2.EstadoCfeRecibido ObtenerEstadoCfeRecibido(string rut, string rutRecibido, int tipoCfe, string serieCfe, int numeroCfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ucfe.uruware.com/IConsultaCfe/GenerarImagenCfeRecibido", ReplyAction="http://ucfe.uruware.com/IConsultaCfe/GenerarImagenCfeRecibidoResponse")]
        byte[][] GenerarImagenCfeRecibido(string rut, string rutRecibido, int tipoCfe, string serieCfe, int numeroCfe, string formato, int dpiX, int dpiY);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaCfeChannel : InterfazWeb.ServiceReference2.IConsultaCfe, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaCfeClient : System.ServiceModel.ClientBase<InterfazWeb.ServiceReference2.IConsultaCfe>, InterfazWeb.ServiceReference2.IConsultaCfe {
        
        public ConsultaCfeClient() {
        }
        
        public ConsultaCfeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaCfeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaCfeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaCfeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InterfazWeb.ServiceReference2.Comprobante[] ComprobantesPorEmpresaDenegadosPorDgi(string rut, System.DateTime fechaComprobante) {
            return base.Channel.ComprobantesPorEmpresaDenegadosPorDgi(rut, fechaComprobante);
        }
        
        public int ComprobantesPorEmpresaPorSerEnviadosADgi(string rut, System.DateTime fechaComprobante) {
            return base.Channel.ComprobantesPorEmpresaPorSerEnviadosADgi(rut, fechaComprobante);
        }
        
        public InterfazWeb.ServiceReference2.Comprobante[] ComprobantesPorSucursalDenegadosPorDgi(string codigoComercio, System.DateTime fechaComprobante) {
            return base.Channel.ComprobantesPorSucursalDenegadosPorDgi(codigoComercio, fechaComprobante);
        }
        
        public int ComprobantesPorSucursalPorSerEnviadosADgi(string codigoComercio, System.DateTime fechaComprobante) {
            return base.Channel.ComprobantesPorSucursalPorSerEnviadosADgi(codigoComercio, fechaComprobante);
        }
        
        public InterfazWeb.ServiceReference2.Comprobante[] ComprobantesPorCajaDenegadosPorDgi(string codigoTerminal, System.DateTime fechaComprobante) {
            return base.Channel.ComprobantesPorCajaDenegadosPorDgi(codigoTerminal, fechaComprobante);
        }
        
        public int ComprobantesPorCajaPorSerEnviadosADgi(string codigoTerminal, System.DateTime fechaComprobante) {
            return base.Channel.ComprobantesPorCajaPorSerEnviadosADgi(codigoTerminal, fechaComprobante);
        }
        
        public string ConsultaHtmlPorNumero(string rut, int tipoCfe, string serieCfe, int numeroCfe) {
            return base.Channel.ConsultaHtmlPorNumero(rut, tipoCfe, serieCfe, numeroCfe);
        }
        
        public string ConsultaHtmlConMontoYCodigo(string rut, int tipoCfe, string serieCfe, int numeroCfe, string monto, string codigoSeguridad) {
            return base.Channel.ConsultaHtmlConMontoYCodigo(rut, tipoCfe, serieCfe, numeroCfe, monto, codigoSeguridad);
        }
        
        public InterfazWeb.ServiceReference2.RespuestaConsultaCfe ConsultaAvanzadaConMontoYCodigo(string rut, int tipoCfe, string serieCfe, int numeroCfe, string monto, string codigoSeguridad) {
            return base.Channel.ConsultaAvanzadaConMontoYCodigo(rut, tipoCfe, serieCfe, numeroCfe, monto, codigoSeguridad);
        }
        
        public byte[] ObtenerPdf(string rut, int tipoCfe, string serieCfe, int numeroCfe) {
            return base.Channel.ObtenerPdf(rut, tipoCfe, serieCfe, numeroCfe);
        }
        
        public byte[][] GenerarImagen(string rut, int tipoCfe, string serieCfe, int numeroCfe, string formato, int dpiX, int dpiY) {
            return base.Channel.GenerarImagen(rut, tipoCfe, serieCfe, numeroCfe, formato, dpiX, dpiY);
        }
        
        public byte[] ObtenerPdfConParametros(string rut, int tipoCfe, string serieCfe, int numeroCfe, string[] nombreParametros, string[] valoresParametros) {
            return base.Channel.ObtenerPdfConParametros(rut, tipoCfe, serieCfe, numeroCfe, nombreParametros, valoresParametros);
        }
        
        public byte[][] GenerarImagenConParametros(string rut, int tipoCfe, string serieCfe, int numeroCfe, string formato, int dpiX, int dpiY, string[] nombreParametros, string[] valoresParametros) {
            return base.Channel.GenerarImagenConParametros(rut, tipoCfe, serieCfe, numeroCfe, formato, dpiX, dpiY, nombreParametros, valoresParametros);
        }
        
        public byte[] ObtenerPdfCfeRecibido(string rut, string rutRecibido, int tipoCfe, string serieCfe, int numeroCfe) {
            return base.Channel.ObtenerPdfCfeRecibido(rut, rutRecibido, tipoCfe, serieCfe, numeroCfe);
        }
        
        public InterfazWeb.ServiceReference2.EstadoCfeRecibido ObtenerEstadoCfeRecibido(string rut, string rutRecibido, int tipoCfe, string serieCfe, int numeroCfe) {
            return base.Channel.ObtenerEstadoCfeRecibido(rut, rutRecibido, tipoCfe, serieCfe, numeroCfe);
        }
        
        public byte[][] GenerarImagenCfeRecibido(string rut, string rutRecibido, int tipoCfe, string serieCfe, int numeroCfe, string formato, int dpiX, int dpiY) {
            return base.Channel.GenerarImagenCfeRecibido(rut, rutRecibido, tipoCfe, serieCfe, numeroCfe, formato, dpiX, dpiY);
        }
    }
}
